// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 AppThere Loki contributors

//! `loki-presentation` library — Dioxus Native presentation components and routing.

// The only `unsafe` in this binary is the Android FFI entry point, generated by
// `loki_app_shell::android_main!` with its own scoped `#[allow(unsafe_code)]`
// (Spec 01 audit A-7). Everything else is `deny`-clean.
#![deny(unsafe_code)]

pub mod app;
pub mod error;
pub mod new_document;
pub mod recent_documents;
pub mod routes;
pub mod tabs;
pub mod utils;

// Android NativeActivity entry point. Shared body lives in
// `loki_app_shell::android_main!` so the three suite binaries don't each carry a
// copy (Spec 01 audit A-14).
loki_app_shell::android_main!(
    tag = "LOKI-PRESENT",
    root = app::App,
    file_access = activity_ptr
);
