// Copyright 2024-2026 AppThere
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Top-level ODF document and body model types.
//!
//! [`OdfDocument`] is the root of the intermediate representation, holding
//! the version metadata and the parsed body tree. Body content is modelled by
//! [`OdfBodyChild`], which captures paragraphs, headings, lists, tables, table
//! of contents sections, and generic sections.
//!
//! Page layout and master-page types defined here are referenced by
//! [`super::styles::OdfStylesheet`].

use super::paragraph::OdfParagraph;
use super::tables::OdfTable;
use crate::version::OdfVersion;

// ── Root document ──────────────────────────────────────────────────────────────

/// The parsed ODF document, prior to mapping into `loki_doc_model` types.
///
/// ODF 1.3 §3.1 (`office:document-content` + `office:body`).
#[derive(Debug, Clone)]
pub(crate) struct OdfDocument {
    /// The ODF specification version detected in the source file.
    pub version: OdfVersion,
    /// `true` if the `office:version` attribute was absent (valid for ODF 1.1).
    pub version_was_absent: bool,
    /// Top-level children of `office:text`.
    pub body_children: Vec<OdfBodyChild>,
}

// ── Body content ───────────────────────────────────────────────────────────────

/// A top-level child of the `office:text` element.
///
/// ODF 1.3 §3.1 — the body of a text document contains paragraphs, headings,
/// lists, tables, table-of-contents sections, and named sections.
#[derive(Debug, Clone)]
pub(crate) enum OdfBodyChild {
    /// A body paragraph (`text:p`). ODF 1.3 §5.1.
    Paragraph(OdfParagraph),
    /// A heading (`text:h`) — an [`OdfParagraph`] with `is_heading = true`.
    /// ODF 1.3 §5.1.
    Heading(OdfParagraph),
    /// A list (`text:list`). ODF 1.3 §5.3.
    List(OdfList),
    /// A table (`table:table`). ODF 1.3 §9.1.
    Table(OdfTable),
    /// A table of contents (`text:table-of-content`). ODF 1.3 §7.5.
    TableOfContent(OdfTableOfContent),
    /// A named text section (`text:section`). ODF 1.3 §5.4.
    Section(OdfSection),
    /// Any body-level element not specifically modelled above.
    Other,
}

// ── Lists ──────────────────────────────────────────────────────────────────────

/// An ODF list (`text:list`). ODF 1.3 §5.3.
#[derive(Debug, Clone)]
pub(crate) struct OdfList {
    /// `xml:id` — unique list identity used by `continue-list`. ODF 1.2+.
    pub xml_id: Option<String>,
    /// `text:style-name` — the list style applied to this list.
    pub style_name: Option<String>,
    /// `text:continue-list` — `xml:id` of a previous list whose numbering
    /// is continued. ODF 1.2+.
    pub continue_list: Option<String>,
    /// `text:continue-numbering` — if `true`, numbering continues from the
    /// preceding list at the same level.
    pub continue_numbering: bool,
    /// Items in this list, in document order.
    pub items: Vec<OdfListItem>,
}

/// An item in an [`OdfList`] (`text:list-item`). ODF 1.3 §5.3.
#[derive(Debug, Clone)]
pub(crate) struct OdfListItem {
    /// `text:start-value` — overrides the counter for this item (restarts
    /// numbering from the given value).
    pub start_value: Option<u32>,
    /// Children of this list item.
    pub children: Vec<OdfListItemChild>,
}

/// A child of an [`OdfListItem`].
///
/// List items may contain paragraphs, headings (treated as paragraphs with a
/// heading style in ODF), or nested lists. ODF 1.3 §5.3.
#[derive(Debug, Clone)]
pub(crate) enum OdfListItemChild {
    /// A paragraph inside the list item.
    Paragraph(OdfParagraph),
    /// A heading inside the list item (rare but valid).
    Heading(OdfParagraph),
    /// A nested list (`text:list` inside `text:list-item`).
    List(OdfList),
}

// ── Table of contents ──────────────────────────────────────────────────────────

/// A table-of-contents section (`text:table-of-content`). ODF 1.3 §7.5.
///
/// The generated body paragraphs are preserved so they can be re-emitted
/// verbatim during export (the TOC is typically regenerated by the
/// application on open).
#[derive(Debug, Clone)]
pub(crate) struct OdfTableOfContent {
    /// `text:name` — logical name of this TOC.
    pub name: Option<String>,
    /// `text:outline-level` from the source element (1–10).
    pub source_outline_level: u8,
    /// The pre-rendered TOC paragraphs from the `text:index-body` element.
    pub body_paragraphs: Vec<OdfParagraph>,
}

// ── Sections ───────────────────────────────────────────────────────────────────

/// A named text section (`text:section`). ODF 1.3 §5.4.
///
/// Sections may contain any body-level content and can be nested.
#[derive(Debug, Clone)]
pub(crate) struct OdfSection {
    /// `text:name` — unique section name.
    pub name: Option<String>,
    /// `text:style-name` — section style reference.
    pub style_name: Option<String>,
    /// Body children inside this section.
    pub children: Vec<OdfBodyChild>,
}

// ── Page layout ────────────────────────────────────────────────────────────────

/// A page layout definition (`style:page-layout`). ODF 1.3 §16.5.
///
/// Defines the physical page dimensions and margins used by a master page.
/// All length values are raw ODF attribute strings (e.g. `"21cm"`).
#[derive(Debug, Clone)]
pub(crate) struct OdfPageLayout {
    /// `style:name` — identifier referenced by `style:master-page`.
    pub name: String,
    /// `fo:page-width` — physical page width.
    pub page_width: Option<String>,
    /// `fo:page-height` — physical page height.
    pub page_height: Option<String>,
    /// `fo:margin-top` — top margin.
    pub margin_top: Option<String>,
    /// `fo:margin-bottom` — bottom margin.
    pub margin_bottom: Option<String>,
    /// `fo:margin-left` — left (gutter) margin.
    pub margin_left: Option<String>,
    /// `fo:margin-right` — right margin.
    pub margin_right: Option<String>,
    /// `style:print-orientation` — `"portrait"` or `"landscape"`.
    pub print_orientation: Option<String>,
    /// Header area properties, if a `style:header-style` child is present.
    pub header_props: Option<OdfHeaderFooterProps>,
    /// Footer area properties, if a `style:footer-style` child is present.
    pub footer_props: Option<OdfHeaderFooterProps>,
}

/// Properties for the header or footer area of a page layout.
///
/// ODF 1.3 §16.5 `style:header-style` / `style:footer-style`.
#[derive(Debug, Clone)]
pub(crate) struct OdfHeaderFooterProps {
    /// `svg:min-height` — minimum height of the header or footer area.
    pub min_height: Option<String>,
    /// `fo:margin` — shorthand margin inside the header or footer.
    pub margin: Option<String>,
}

/// A master page definition (`style:master-page`). ODF 1.3 §16.9.
///
/// Master pages link a page layout to optional header and footer content.
#[derive(Debug, Clone)]
pub(crate) struct OdfMasterPage {
    /// `style:name` — identifier (e.g. `"Standard"`, `"First_20_Page"`).
    pub name: String,
    /// `style:page-layout-name` — references an [`OdfPageLayout`].
    pub page_layout_name: String,
    /// Paragraphs inside `style:header`, if present.
    pub header: Option<Vec<OdfParagraph>>,
    /// Paragraphs inside `style:footer`, if present.
    pub footer: Option<Vec<OdfParagraph>>,
}

// ── Document metadata ──────────────────────────────────────────────────────────

/// Document metadata extracted from `meta.xml`.
///
/// ODF 1.3 §3.1 `office:meta` and the Dublin Core / ODF meta elements
/// therein (§3.1.1–§3.1.18).
#[derive(Debug, Clone, Default)]
pub(crate) struct OdfMeta {
    /// `dc:title` — document title.
    pub title: Option<String>,
    /// `dc:creator` — the author who last saved the document.
    pub creator: Option<String>,
    /// `dc:description` — document description or abstract.
    pub description: Option<String>,
    /// `meta:creation-date` — ISO-8601 creation timestamp.
    pub created: Option<String>,
    /// `dc:date` — ISO-8601 last-modification timestamp.
    pub modified: Option<String>,
    /// `meta:editing-cycles` — number of times the document was saved.
    pub editing_cycles: Option<u32>,
}
