// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 AppThere Loki contributors

//! `loki-spreadsheet` library — Dioxus Native spreadsheet components and routing.
//!
//! Exposes the module tree for integration testing and potential embedding.
//! The binary entry point lives in `main.rs` and calls [`app::App`].

// Pre-existing pattern in routes/editor/editor_inner.rs — structural refactor deferred
#![allow(clippy::manual_strip)]
// The only `unsafe` in this binary is the Android FFI entry point, generated by
// `loki_app_shell::android_main!` with its own scoped `#[allow(unsafe_code)]`
// (Spec 01 audit A-7). Everything else is `deny`-clean.
#![deny(unsafe_code)]

pub mod app;
pub mod error;
pub mod new_document;
pub mod recent_documents;
pub mod routes;
pub mod sessions;
pub mod tabs;
pub mod utils;

// Android NativeActivity entry point. Shared body lives in
// `loki_app_shell::android_main!` so the three suite binaries don't each carry a
// copy (Spec 01 audit A-14).
loki_app_shell::android_main!(
    tag = "LOKI-SHEET",
    root = app::App,
    file_access = activity_ptr
);
