// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 AppThere Loki contributors

//! Cross-version golden test for the persisted Loro wire format (audit finding
//! F13).
//!
//! Every other bridge test is `document_to_loro → loro_to_document` in one
//! process, so a *coordinated* rename of a mark key or a schema key (writer +
//! reader + constant, changed together) passes the whole suite while orphaning
//! every CRDT snapshot already on disk and every oplog the collaboration server
//! holds. This file breaks the symmetry two ways:
//!
//! 1. [`golden_snapshot_reconstructs_the_expected_document`] imports a
//!    **checked-in binary snapshot** produced by an earlier build and asserts
//!    that today's reader reconstructs it.
//! 2. [`writer_emits_the_literal_mark_vocabulary`] asserts the *writer* still
//!    emits the exact key and value **literals** — spelled out here, never via
//!    the `MARK_*` constants, so renaming a constant cannot move the goalposts.
//!
//! ## Fixture provenance
//!
//! `tests/fixtures/loro_snapshot_v1.bin` was captured on **2026-08-25** from
//! `document_to_loro(&fixture_document())` exported with
//! `ExportMode::snapshot()`, on the implementation as of that date. It is
//! **not** regenerated by the suite and must not be regenerated to make a
//! failure go away.
//!
//! **A change that breaks these tests is a breaking change to a persisted
//! format.** It orphans stored documents and server oplogs, so it needs a
//! deliberate migration — a reader that still accepts the old shape, in the
//! spirit of `loro_bridge::decode`'s v1 border strings — not a new fixture.

use loki_doc_model::content::attr::NodeAttr;
use loki_doc_model::content::block::Block;
use loki_doc_model::content::inline::{Inline, NoteKind, StyledRun};
use loki_doc_model::content::table::row::Cell;
use loki_doc_model::content::table::{Row, Table, TableBody, TableCaption, TableFoot, TableHead};
use loki_doc_model::document::Document;
use loki_doc_model::loro_bridge::{document_to_loro, loro_to_document};
use loki_doc_model::loro_schema::{KEY_BLOCKS, KEY_CONTENT, KEY_SECTIONS};
use loki_doc_model::style::props::char_props::CharProps;
use loki_doc_model::style::props::revision::{RevisionKind, RevisionMark};
use loki_primitives::color::DocumentColor;
use loro::{LoroDoc, LoroValue, TextDelta};

/// The captured bytes. `include_bytes!` (rather than a runtime read) so a
/// missing fixture is a compile error, not a skipped test.
const GOLDEN: &[u8] = include_bytes!("fixtures/loro_snapshot_v1.bin");

fn para(text: &str) -> Block {
    Block::Para(vec![Inline::Str(text.into())])
}

fn run_with(props: CharProps, text: &str) -> Inline {
    Inline::StyledRun(StyledRun {
        style_id: None,
        direct_props: Some(Box::new(props)),
        content: vec![Inline::Str(text.into())],
        attr: NodeAttr::default(),
    })
}

/// The colour the fixture's coloured run carries, as a literal.
fn fixture_colour() -> DocumentColor {
    DocumentColor::from_hex("#C81E1E").expect("literal hex colour")
}

/// The revision mark the fixture's tracked run carries, as a literal.
fn fixture_revision() -> RevisionMark {
    RevisionMark {
        kind: RevisionKind::Insertion,
        author: Some("Ada Lovelace".into()),
        date: Some("2026-07-07T12:00:00Z".into()),
        id: Some("rev-3".into()),
    }
}

/// The document the fixture was captured from — deliberately small, but wide
/// enough to touch the vocabulary the audit flagged as unpinned: the bold mark,
/// the colour codec, the revision codec, the native table schema, the native
/// note container, and the opaque-JSON fallback.
///
/// Each marked run is the **last** inline in its paragraph. That is deliberate:
/// every character mark is registered `ExpandType::After`, so text inserted at
/// a mark's trailing edge is swallowed by it (the hazard the `replace_text` doc
/// comment in `loro_mutation::text` describes). Keeping marked runs at the tail
/// keeps this fixture about the *wire format* rather than about that expansion
/// behaviour.
fn fixture_document() -> Document {
    let mut doc = Document::new();
    doc.meta.title = Some("Golden Snapshot".into());

    let coloured = CharProps {
        color: Some(fixture_colour()),
        ..Default::default()
    };
    let tracked = CharProps {
        revision: Some(fixture_revision()),
        ..Default::default()
    };

    doc.sections[0].blocks = vec![
        Block::Heading(1, NodeAttr::default(), vec![Inline::Str("Golden".into())]),
        Block::Para(vec![
            Inline::Str("plain ".into()),
            Inline::Strong(vec![Inline::Str("bold".into())]),
        ]),
        Block::Para(vec![Inline::Str("red: ".into()), run_with(coloured, "red")]),
        Block::Para(vec![
            Inline::Str("tracked: ".into()),
            run_with(tracked, "added"),
        ]),
        Block::Para(vec![
            Inline::Str("see".into()),
            Inline::Note(NoteKind::Footnote, vec![para("note body")]),
        ]),
        Block::Table(Box::new(Table {
            attr: NodeAttr::default(),
            caption: TableCaption::default(),
            width: None,
            col_specs: Vec::new(),
            head: TableHead {
                attr: NodeAttr::default(),
                rows: vec![Row::new(vec![
                    Cell::simple(vec![para("H1")]),
                    Cell::simple(vec![para("H2")]),
                ])],
            },
            bodies: vec![TableBody::from_rows(vec![Row::new(vec![
                Cell::simple(vec![para("a")]),
                Cell::simple(vec![para("b")]),
            ])])],
            foot: TableFoot::empty(),
        })),
        // No native mapping — exercises the opaque-JSON snapshot shape.
        Block::DefinitionList(vec![(
            vec![Inline::Str("term".into())],
            vec![vec![para("definition")]],
        )]),
    ];
    doc
}

/// Loads the checked-in snapshot into a fresh, unconfigured `LoroDoc` — the
/// same way `loki-server-collab`'s compactor loads a persisted snapshot.
fn golden_document() -> Document {
    let loro = LoroDoc::new();
    loro.import(GOLDEN)
        .expect("the checked-in snapshot imports");
    loro_to_document(&loro).expect("the checked-in snapshot reads back")
}

/// The direct `CharProps` of the last inline of `block`, which every fixture
/// paragraph places its marked run in.
fn tail_run_props(block: &Block) -> CharProps {
    let Block::Para(inlines) = block else {
        panic!("expected a Para, got {block:?}");
    };
    match inlines.last() {
        Some(Inline::StyledRun(run)) => *run
            .direct_props
            .clone()
            .expect("the tail run must carry direct props"),
        other => panic!("expected a trailing StyledRun, got {other:?}"),
    }
}

// ── 1. The reader still understands bytes written by an earlier build ─────────

#[test]
fn golden_snapshot_reconstructs_the_expected_document() {
    let doc = golden_document();
    let expected = fixture_document();

    assert_eq!(
        doc.meta.title.as_deref(),
        Some("Golden Snapshot"),
        "metadata schema key drifted"
    );
    assert_eq!(doc.sections.len(), 1);
    let blocks = &doc.sections[0].blocks;
    assert_eq!(blocks.len(), 7, "block count drifted: {blocks:#?}");

    // Heading: block-type key + level key.
    assert_eq!(blocks[0], expected.sections[0].blocks[0]);

    // Bold mark. Wrapper inlines are re-derived as styled runs, so the shape
    // differs from the source document by design — the *mark* is the contract.
    assert_eq!(
        blocks[1],
        Block::Para(vec![
            Inline::Str("plain ".into()),
            run_with(
                CharProps {
                    bold: Some(true),
                    ..Default::default()
                },
                "bold",
            ),
        ]),
        "the bold mark did not survive the persisted snapshot"
    );

    // Colour codec.
    assert_eq!(
        tail_run_props(&blocks[2]).color,
        Some(fixture_colour()),
        "the character-colour codec did not survive the persisted snapshot"
    );

    // Revision codec (the same packed string F7 pins directly).
    assert_eq!(
        tail_run_props(&blocks[3]).revision,
        Some(fixture_revision()),
        "the revision codec did not survive the persisted snapshot"
    );

    // Native note container.
    assert_eq!(
        blocks[4],
        Block::Para(vec![
            Inline::Str("see".into()),
            Inline::Note(NoteKind::Footnote, vec![para("note body")]),
        ]),
        "the footnote anchor/body schema did not survive the persisted snapshot"
    );

    // Native table schema (skeleton + live per-cell block lists).
    assert_eq!(
        blocks[5], expected.sections[0].blocks[5],
        "the native table schema did not survive the persisted snapshot"
    );

    // Opaque-JSON fallback.
    assert_eq!(
        blocks[6], expected.sections[0].blocks[6],
        "the opaque-snapshot JSON shape did not survive the persisted snapshot"
    );
}

#[test]
fn todays_writer_still_produces_what_the_golden_reader_sees() {
    // The inversion of the test above: writing the same document today and
    // reading it back must land on the same value as reading the 2026-08-25
    // bytes. When only this one fails, the *reader* drifted; when only the
    // golden one fails, the change is a persisted-format break.
    let live = loro_to_document(&document_to_loro(&fixture_document()).expect("to loro"))
        .expect("from loro");
    assert_eq!(
        live.sections[0].blocks,
        golden_document().sections[0].blocks
    );
}

// ── 2. The writer still emits the literal key/value vocabulary ────────────────

/// The rich-text delta of the block at `index` in section 0.
fn block_delta(loro: &LoroDoc, index: usize) -> Vec<TextDelta> {
    let sections = loro.get_list(KEY_SECTIONS);
    let sec = sections
        .get(0)
        .and_then(|v| v.into_container().ok())
        .and_then(|c| c.into_map().ok())
        .expect("section 0");
    let blocks = sec
        .get(KEY_BLOCKS)
        .and_then(|v| v.into_container().ok())
        .and_then(|c| c.into_movable_list().ok())
        .expect("blocks list");
    let block = blocks
        .get(index)
        .and_then(|v| v.into_container().ok())
        .and_then(|c| c.into_map().ok())
        .expect("block map");
    let text = block
        .get(KEY_CONTENT)
        .and_then(|v| v.into_container().ok())
        .and_then(|c| c.into_text().ok())
        .expect("block text");
    text.to_delta()
}

/// The attribute value stored under `key` on the trailing span of block `index`.
fn tail_attr(loro: &LoroDoc, index: usize, key: &str) -> Option<LoroValue> {
    let delta = block_delta(loro, index);
    let TextDelta::Insert { attributes, .. } = delta.last()? else {
        return None;
    };
    attributes.as_ref()?.get(key).cloned()
}

#[test]
fn writer_emits_the_literal_mark_vocabulary() {
    // Every string below is written out **as a literal**, never as a `MARK_*`
    // constant: a coordinated rename of the constant plus both sides of the
    // bridge must fail here, because these are the bytes already on disk.
    let loro = document_to_loro(&fixture_document()).expect("to loro");

    assert_eq!(
        tail_attr(&loro, 1, "bold"),
        Some(LoroValue::Bool(true)),
        r#"the bold mark key must stay "bold""#
    );
    assert_eq!(
        tail_attr(&loro, 2, "color"),
        Some(LoroValue::String("#C81E1E".into())),
        r##"the colour mark key must stay "color", encoded as "#RRGGBB""##
    );
    assert_eq!(
        tail_attr(&loro, 3, "revision"),
        Some(LoroValue::String(
            "i\u{1f}Ada Lovelace\u{1f}2026-07-07T12:00:00Z\u{1f}rev-3".into()
        )),
        r#"the revision mark key must stay "revision", packed with US separators"#
    );

    // Inversion: a key that is *not* set must be absent, so the assertions
    // above are reading a specific mark rather than "any attribute at all".
    assert_eq!(tail_attr(&loro, 1, "color"), None);
    assert_eq!(tail_attr(&loro, 2, "bold"), None);
    assert_eq!(tail_attr(&loro, 3, "bold"), None);
}
