// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 AppThere Loki contributors

//! `loki-text` library — Dioxus Native word-processor components and routing.
//!
//! Exposes the module tree for integration testing and potential embedding.
//! The binary entry point lives in `main.rs` and calls [`app::App`].

// The only `unsafe` in this binary is the Android FFI entry point, generated by
// `loki_app_shell::android_main!` with its own scoped `#[allow(unsafe_code)]`
// (Spec 01 audit A-7). Everything else is `deny`-clean.
#![deny(unsafe_code)]

pub mod app;
pub mod components;
pub mod editing;
pub mod error;
pub mod new_document;
pub mod recent_documents;
pub mod routes;
pub mod sessions;
pub mod tabs;
pub mod utils;

// Android NativeActivity entry point. Shared body lives in
// `loki_app_shell::android_main!` so the three suite binaries don't each carry a
// copy (Spec 01 audit A-14). `null_context`: init_android is a no-op here (the
// JNI context comes from ndk_context) — see the macro docs.
loki_app_shell::android_main!(tag = "LOKI", root = app::App, file_access = null_context);
